#!/bin/sh

# git
# https://computingforgeeks.com/how-to-install-latest-version-of-git-git-2-x-on-centos-7/
#
sudo yum remove -y git*
sudo yum install -y https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
sudo yum install -y git

# bootstrap dotfiles
./bootstrap

# vim
# uninstall vim
sudo yum remove -y vim*

# install ncurses
sudo yum install -y ncurses-devel make gcc

# add repository
# sudo curl -L https://copr.fedorainfracloud.org/coprs/unixcommunity/vim/repo/epel-7/unixcommunity-vim-epel-7.repo -o /etc/yum.repos.d/unixcommunity-vim-epel-7.repo
sudo curl -L https://copr.fedorainfracloud.org/coprs/lantw44/vim-latest/repo/epel-7/lantw44-vim-latest-epel-7.repo -o /etc/yum.repos.d/lantw44-vim.repo
sudo yum install -y vim

# node
curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
sudo yum install -y nodejs

## if you want yarn
#  curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
#  sudo yum install yarn

# javascript lsp install
sudo npm install -g typescript typescript-language-server

# install
./install

# symbolic_link
./symbolic_link
# remove installer
cd $HOME
DOTVER=0.1.4
sudo rm -r dotfiles-$DOTVER-alpha
sudo rm v$DOTVER-alpha.tar.gz
