#!/bin/sh

# dein
cd $HOME
pwd
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
# For example, we just use `~/.cache/dein` as installation directory
sh ./installer.sh ~/.cache/dein
rm ./installer.sh

# tig
cd /tmp
pwd
curl -OL https://github.com/jonas/tig/releases/download/tig-2.5.1/tig-2.5.1.tar.gz
tar zxf tig-2.5.1.tar.gz
cd tig-2.5.1
./configure --prefix=/usr
make
sudo make install

cd ..
sudo rm -r tig-2.5.1.tar.gz
